service: test-gmodelo
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
          - dynamodb:*
          Resource:
            - "arn:aws:dynamodb:*"
        - Effect: "Allow"
          Action:
          - s3:*
          Resource: 
            - "arn:aws:s3:::*"

functions:
  search:
    handler: handler.search
    timeout: 90
    events:
      - http:
          path: search
          method: get
          cors: true